# These are supported funding model platforms

👋 Hi, I’m @gopualakrishna6 My Name is Gopu Alakrishna Nagarajan
👀 I’m interested in ...Helping People affected by Natuaral Disasters, Wars in all Countries
🌱 I’m currently learning ...How to help Humans in this world? How to create a safe and peaceful world without Wars?
💞️ I’m looking to collaborate on ...Fund raising Helping People affected by Natuaral Disasters, Wars in all Countries
📫 How to reach me ... gopualakrishna6@yahoo.com Email ID
+91-99005055351 Whatsapp and Mobile Number
Fund can be sent by using my Google Pay using following UPI IDs:

gopualakrishna-2@okhdfcbank / gopualakrishna-1@okaxis / gopualakrishna-2@oksbi

Paypal account details to transfer fund: @gopualakrishna
gopualakrishna@gmail.com paypal registered email
9900505351 paypal registered mobile number

.

I am a Global Peace Maker, Global Citizen, so Could you please send fund generously to my Bit Coin address given below

Send Fund to my BitCoin Address: 1AiRoneVpLjM92BDf4puKXYgX1TcdvqYxi

UPI Money transfer through Paytm address to send fund 9900505351@paytm


github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
